export const ScreenName = {
    LOGIN: 'login',
    SPLASH:'splash',
    HOME: 'home',
    HOME_TAB: 'home_tab',
    SEARCH:'Search',
    FAVORITE:'favorite',
    PROFILE:'profile'
  };
  export const Icons = {
    HOMEOUTLINE: require('../assets/tabIcons/home-outline.png'),
    HOMEFILLED: require('../assets/tabIcons/home-filled.png'),
    SEARCHOUTLINE: require('../assets/tabIcons/search-outline.png'),
    SEARCHFILLED: require('../assets/tabIcons/search-filled.png'),
    PROFILEOUTLINE: require('../assets/tabIcons/profileOutline.png'),
    PROFILEFILLED: require('../assets/tabIcons/profileField.png'),
    FAVORITEOUTLINE: require('../assets/tabIcons/favorite-outline.png'),
    FAVORITEFILLED: require('../assets/tabIcons/favorite-filled.png'),
    WALLETOUTLINE: require('../assets/tabIcons/walletOutline.png'),
    WALLETFILLED: require('../assets/tabIcons/walletField.png'),
    CLIPBOARDOUTLINE: require('../assets/tabIcons/bookingOutline.png'),
    CLIPBOARDFILLED: require('../assets/tabIcons/bookingField.png'),
    CART: require('../assets/tabIcons/cart.png'),
    SHOPPING_CART: require('../assets/tabIcons/shopping-cart.png'),
    ARROWDOWN: require('../assets/tabIcons/downArrow.png'),
    ARROWRIGHT: require('../assets/starImages/rightArrow.png'),
    LOCATION: require('../assets/locationIcon/raphael--location.png'),
    LOCATIONOUTLINE: require('../assets/starImages/locationOutline.png'),
    STAR: require('../assets/starImages/star.png'),
    STAROUTLINE: require('../assets/starImages/starOutline.png'),
    EDIT: require('../assets/starImages/edit.png'),
    HEADPHONE: require('../assets/starImages/headPhone.png'),
    SETTING: require('../assets/starImages/setting.png'),
    MEMBERSHIP: require('../assets/starImages/membership.png'),
    BOOKINGSCHEDULE: require('../assets/starImages/BookingSchedule.png'),
    ABOUT: require('../assets/starImages/about.png'),
    PAYMENT: require('../assets/starImages/payment.png'),
    GIFT: require('../assets/starImages/gift.png'),
    RIGHT_ARROW: require('../assets/tabIcons/right-arrow.png'),
    // LEFT_ARROW: require('../assets/tabIcons/left-arrow.png'),
    WHATSAPP: require('../assets/starImages/whatsapp.png'),
    FB: require('../assets/starImages/messenger.png'),
    LINK: require('../assets/starImages/copylink.png'),
    OFFERTAG: require('../assets/starImages/offertag.png'),
    DISCOUNT: require('../assets/starImages/discount.png'),
    GUARANTEE: require('../assets/starImages/guarantee.png'),
    CART_BXS: require('../assets/starImages/bxs--cart.png'),
    BLACKDOT: require('../assets/starImages/blackDot.png'),
    PLUS: require('../assets/starImages/plus.png'),
    MINUS: require('../assets/starImages/minus.png'),
    SHARE: require('../assets/starImages/Share.png'),
    CROSSWHITE: require('../assets/tabIcons/cross-white.png'),
    WHITETAG: require('../assets/tabIcons/whiteTag.png'),
    Menu: require('../assets/tabIcons/menu.png'),
    THREEDOT:require('../assets/starImages/menu.png'),
    CREDITCARD:require('../assets/starImages/credit-card.png'),
    RIGHTCHACK:require('../assets/starImages/Rightcheck.png'),
    BRUSH:require('../assets/browseCategoryImages/cleaning.png'),
    WASHING:require('../assets/browseCategoryImages/washingmachine.png'),
    IRONING:require('../assets/browseCategoryImages/ironing.png'),
    SEE_ALL_ARROW:require('../assets/browseCategoryImages/seeallarrow.png'),
    ADD_BUTTON:require('../assets/browseCategoryImages/addbutton.png'),
    SUCCESS: require('../assets/browseCategoryImages/success.png'),
    REJECT: require('../assets/browseCategoryImages/error.png'),
    CROSS: require('../assets/browseCategoryImages/cross.png'),
    TICK: require('../assets/browseCategoryImages/tick.png'),
  
  };
  